Docs: Fix RTD docs build process
Since commit 9b48e5c8ca4cde348315d85ecbbda4740a5840da  ReadTheDocs (RTD)
wasn't able to build the docs. The stacktrace from the RTD build show
this error:

  ExtensionError: Could not import extension oslo_config.sphinxconfiggen
  (exception: No module named oslo_config.sphinxconfiggen)

The reason is, that RTD *doesn't* use tox targets to create the docs.
It also cannot be configured to use tox. It uses it's own chain of
commands to build, like these (simplified) commands:

  $ python -mvirtualenv  networking-dpm/envs/latest
  $ python networking-dpm/envs/latest/bin/pip install -r test-requirements.txt
  $ python networking-dpm/envs/latest/bin/sphinx-build -T -E \
  -b readthedocs . _build/html

This means RTD is not able to pull in the dependencies we specified in
the "tox.ini" base target:

    [testenv]
    deps = -r{toxinidir}/test-requirements.txt
           -r{toxinidir}/requirements.txt
           -egit+https://github.com/openstack/neutron#egg=neutron

The needed python package is "oslo.config", which gets pulled into our
tox targets via the specified dependency to neutron, that's why the initial
commit didn't fail the docs testing job.

This change adds "oslo.config" to "test-requirements.txt".

An alternative approach would have been to introduces a dedicated
"docs-requirements.txt" file, which will only be used by building docs.
On the other hand, this wouldn't work in upstream testing jobs,
because they don't call `tox -e docs` but the command
`tox -evenv -- python setup.py build_sphinx` and having the docs
deps in the "venv" tox target doesn't help.

Closes bug: #1660572

Change-Id: I96b3e1d47adc71699406da12859441ee92e009ab