Use TYPE_FLAT constant from neutron-lib
Launch of an instance fails with:
"AttributeError: 'module' object has no attribute 'TYPE_FLAT'"

Patch [1] removed the constant as it's now present in neutron-lib. Need to use
it from there.

[1] https://github.com/openstack/neutron/commit/95f1e03446070fa3fc5afbad796fbf661d6e22e9

Change-Id: I478d057e7cac4749434933c87964a013ce8d31da